### ISSUE TITLE
Selecting backwards dates in poll creation

### ISSUE THREAD

**Issue by ashrafchowdury** [lukevella/rallly#1002]
**Describe the bug**

Currently, there is a bug in the poll creation page where users can select dates in the past when creating new polls. **Users can select past dates and can end the poll on past.** This functionality allows users to schedule polls for dates that have already passed, causing inconsistencies in the system and confusion among users.

**To Reproduce**

1. Go to the Polls page
2. Click on 'New Poll' button
3. Scroll down to Calendar section
4. Select dates from the past

**Expected behavior**
The system should restrict users from selecting dates that have already passed when scheduling polls.

**Screenshots**

https://github.com/lukevella/rallly/assets/87828904/49c08c3c-9b83-42cf-8925-afe75aa800c8

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser [e.g. chrome, edge]
- Version latest

**Comment by ashrafchowdury** [comment]
**I would like to work on this issue if it gets approved** 🙌

**Comment by lukevella** [comment]
The components that require updating to solve this issue are due to be replaced. It's not worth the effort to try to fix this now. It's true that selecting past dates is not useful for our intended use cases and should probably not be allowed but it's not a high priority issue and it will be fixed in due time.
