### ISSUE TITLE
Dates displaying different for different users

### ISSUE THREAD

**Issue by terrance888** [lukevella/rallly#105]
For me, I put only mondays.

For my schedulers, I put only Sundays.

Needless to say, this is a bit wack
Mine:
![unknown](https://user-images.githubusercontent.com/64514250/152907627-341abc76-3e00-4f5c-bf9a-82ef1c3c4ff1.png)
User 1:
![unknown](https://user-images.githubusercontent.com/64514250/152907650-16681742-4394-495a-b026-b56f8e577193.png)
User 2:
![unknown](https://user-images.githubusercontent.com/64514250/152907657-e0724688-4781-4453-b7ab-13f9f7f73e2d.png)
.

**Comment by lukevella** [comment]
Hi @terrance888, thanks for raising this. The issue here is that date values are stored in the database with timezone information that is determined by the machine of whoever created the event. This means people in different timezones can end up seeing different dates. Clearly an oversight from my end here and I apologize for that. I have already spent some time trying to fix this but at this point it might be better to simply fix this in the new version of Rallly which I'm currently working on and hopefully will be able to release very soon. Sorry if this issue caused you any trouble. I'll keep this issue open for now but I don't expect a fix for this in the current version.

**Comment by terrance888** [comment]
Hi Luke,

Thanks for your response. It’s weird because the time zone difference involved is eastern time versus central time. Is there anything we can do on our side/user end for this to display correctly? Aka a workaround?

Thanks,
Terrance

**Comment by lukevella** [comment]
I'm afraid other than setting your computers/devices to the timezone the event was created in there is not much else that can be done at the moment.

**Comment by robertlong13** [comment]
@lukevella I'm pretty sure there is a one-line fix to this.

It appears that when the creator initially creates the event, the dates are stored as midnight local time for the creator. This utterly breaks things if any participants are even one time-zone west of the creator. If you change this so that the datepicker creates the dates as _noon_ local time instead, it will at least fix 99% of the problem. I think you can fix it in datepicker.directive.js

change
```
var today = Date.today(), activeDate = today.clone();
```
to
```
var today = new Date(Date.getYear(), Date.getMonth(), Date.getDay(), 12), activeDate = today.clone();
```

Of course, the _correct_ thing to do would be to handle dates in a locale-agnostic fashion everywhere, but that's a little harder and I can't quite figure out how to do that (because I have zero experience with webapp development).

I was planning to test the above fix and open a pull request, but unfortunately, the build instructions are broken, and I don't have enough experience to figure out what's wrong there.

**Comment by UnbelievableSalt** [comment]
> Hi @terrance888, thanks for raising this. The issue here is that date values are stored in the database with timezone information that is determined by the machine of whoever created the event. This means people in different timezones can end up seeing different dates. Clearly an oversight from my end here and I apologize for that. I have already spent some time trying to fix this but at this point it might be better to simply fix this in the new version of Rallly which I'm currently working on and hopefully will be able to release very soon. Sorry if this issue caused you any trouble. I'll keep this issue open for now but I don't expect a fix for this in the current version.

Fuck you Luke.

**Comment by lukevella** [comment]
The new version fixes this issue. Closing.
