### ISSUE TITLE
Not an issue per-se. Plus asks from a user/non-coder 

### ISSUE THREAD

**Issue by derekatwestern** [lukevella/Rallly#11]
Is it desirable for me to be able to change other's votes? My concern would be errors more than malicious voters. Also, I would prefer to cast a "weighted" vote. First, second, third choice, which yields a more complex value for each option, especially if a time option were added.
That being said, thanks for undertaking this.  Hits a huge, sweet need my volunteer organization has. Saves perhaps 2 dozen emails with reply-all and no integrated tabulation.

**Comment by lukevella** [comment]
Hey Derek, thanks for writing and glad to hear you found Rallly useful. To answer your concerns...

Rallly doesn't require you to login, and for most people this is great. However because of this it is unable to identify who a user is so it's not possible to prevent people from changing someone else's vote because it can not know which vote belongs to you.

As for weighted votes, I've created a new issue (see #12) with this suggestion so I can get to it when I have some time.
