### ISSUE TITLE
Valid email addresses are rejected

### ISSUE THREAD

**Issue by paulmenzel** [lukevella/rallly#1343]
On rally.co participant in a survey and enter an email address containing / and ~ in the local part. Such an email is incorrectly rejected, for example <a+rally.co~/@example.net>.

**Comment by chrhi** [comment]
Thanks for pointing this out! It looks like the current validation might be stricter than necessary, as `/` and `~` can technically be valid characters in the local part of an email address according to the email standards (RFC 5321/5322). 

It might be worth revisiting the email validation logic to accommodate these characters. This would allow users to input email addresses that are valid but currently rejected. Just wanted to bring this up in case the maintainers want to address it. Appreciate the great work on the project!

**Comment by lukevella** [comment]
We use [zod](https://zod.dev) for email validation and I believe I've found the reason for this issue here: https://github.com/colinhacks/zod/pull/2157

It seems to be a reason why this won't be fixed as well as I have no plans to implement and maintain my own email validation. So I apologize for not being able to use your favorite email address with Rallly 🙏
