### ISSUE TITLE
docker builds should not reference a database

### ISSUE THREAD

**Issue by andrewzah** [lukevella/rallly#170]
https://github.com/lukevella/rallly/blob/357d25305f8162106f363ea2cf81e5f2841b4e53/Dockerfile#L6

Hi, firstly thanks for your work on rallly. However it is not advisable to tie docker builds to a database.
Docker builds should ideally be as idempotent as possible, and database configuration can happen via commands later or entrypoint scripts.

**Comment by lukevella** [comment]
Hi @andrewzah, fair point. The reason why this is there is because when building the prisma client,`DATABASE_URL` needs to be set to generate the prisma client which happens after installing dependencies. You are right though that this isn't a good idea since it wouldn't be possible to distribute a prebuilt image in this way. Thanks for raising.

**Comment by LarsHaalck** [comment]
If I understand it correctly, you can set it to something different during generate (i.e. a placeholder) and set it to the correct value in the client during runtime using this: https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#datasources
