### ISSUE TITLE
Mail with magic link domain missing

### ISSUE THREAD

**Issue by Tuphal** [lukevella/rallly#251]
**Describe the bug**
In the mail sent with the magic link, the domain is missing in the link:
![grafik](https://user-images.githubusercontent.com/42291781/181477982-9bee563a-5f01-46d5-81fa-b79ec1505be2.png)

The link is working, when manually inserting the domain.

docker compose with the correct/working URL:
![grafik](https://user-images.githubusercontent.com/42291781/181478233-e109a794-2c78-41c9-bf4d-68afbf0345da.png)

I used todays repo to create an image in portainer to use in the compose

**Comment by Tuphal** [comment]
I have seen, that on all emails, the domain is missing:

![grafik](https://user-images.githubusercontent.com/42291781/181479245-ee49f4e0-811a-4b34-8b06-6b1d13bc1167.png)

![grafik](https://user-images.githubusercontent.com/42291781/181479365-27377297-e50e-48d5-ab5b-cff4dc9bbfdd.png)

**Comment by lukevella** [comment]
This is what `NEXT_PUBLIC_BASE_URL` is for. Are you able to confirm that the value is set within the container? i.e. you 
 need to print out the env vars in the container to make sure it's set.

**Comment by Tuphal** [comment]
It seems to be set:
![grafik](https://user-images.githubusercontent.com/42291781/181482129-b3ae108e-9c28-4769-9587-2bb046e6d9a5.png)

other env-variables are working as emails are being sent.

**Comment by lukevella** [comment]
Looking at your config again I see you're setting `NEXT_PUBLIC_BASE_URL` through environments but the dockerfile requires it during build so it needs to be passed as an arg during build. See:

https://github.com/lukevella/rallly/blob/main/docker-compose.yml#L16

This was done because previously we used this value on statically rendered pages which required the value to be present during build. I don't think this is the case anymore. So we can transition to only use `NEXT_PUBLIC_BASE_URL` on the server side which would mean that this value does not need to be present during build.

In the meantime, if you want this to work properly you will need to pass `NEXT_PUBLIC_BASE_URL` as an argument during build. 

I will keep this open and will close it when this is updated.

**Comment by lukevella** [comment]
@Tuphal any chance you can test out #253 to see if that works for you?

**Comment by Tuphal** [comment]
It is working. The magic link as well as the logo/link is correct.

![grafik](https://user-images.githubusercontent.com/42291781/181515813-40f59266-83e4-43c9-ae19-c1c7ca7f26c6.png)

Thank you !
