### ISSUE TITLE
Open graph tag url incorrect

### ISSUE THREAD

**Issue by andreasdueren** [lukevella/rallly#378]
**Describe the bug**
Currently the URL and image URL for the OG Tag are incorrect and therefore won't load.

is:

```
<meta property="og:url" content="http://localhost:3000">
<meta property="og:type" content="website">
<meta property="og:image" content="http://localhost:3000/og-image-1200.png">
```

should be:

```
<meta property="og:url" content="https://tld.url">
<meta property="og:type" content="website">
<meta property="og:image" content="/og-image-1200.png">
```

**To Reproduce**
1. Go to 'poll.due.ren'
2. look at header code

**Screenshots**
<img width="609" alt="Screenshot 2023-01-02 at 07 38 18" src="https://user-images.githubusercontent.com/46187667/210239022-6e60ac04-153e-43e3-a49c-220093a0ebea.png">
<img width="581" alt="Screenshot 2023-01-02 at 07 38 22" src="https://user-images.githubusercontent.com/46187667/210239026-7a658e26-ed62-4e01-a7b6-e2b2e6ac7e2c.png">

**Comment by nebulade** [comment]
after some debugging, turns out those assets are built during `yarn build` and thus the domain needs to be set via `NEXT_PUBLIC_BASE_URL` at build time. For deployments like Cloudron where all code and app assets are built without knowing the public domain upfront (also as it might change upon app restart) I don't think this is easily solvable. But maybe the devs here have some idea how it could be supported without having to rebuild all static assets on every potential app restart where the domain might have changed.

**Comment by lukevella** [comment]
I think there are/were some files that where being statically generated at build time but you’re right that it would make a lot more sense if URL didn’t need to be specified at build time. Thanks for raising this.

**Comment by nebulade** [comment]
Great, thanks for the fix!
