### ISSUE TITLE
Dates are deselected when I switch between apps on an iPad

### ISSUE THREAD

**Issue by axbom** [lukevella/rallly#457]
I am filling in a poll in the browser (Safari on iPad) and switch app to the calendar to double-check dates. When I switch back, after about 30 seconds or more, the dates I had already selected and dealt with have been deselected so I keep having to start over. In the end I gave up.

**To Reproduce**
1. Go to any poll using Safari on an iPad (have not tested on anything else)
2. Select a few dates (any option: yes, if need be, or no)
3. Leave the browser and open another app (it was the calendar in my case)
4. Wait 30 seconds. 
5. Return to the browser.
6. The dates you selected options for are deselected and back to a question mark

**Expected behavior**
I never want dates to be deselected if I’ve alredy indicated my response on that date.

**Desktop (please complete the following information):**
 - iPadOS
 - Safari
 - All the latest

**Comment by lukevella** [comment]
Hi @axbom. Thanks for reporting this. I believe this happens because there are two separate components for rendering the poll for mobile and for larger screens. These components manage their own state so when unmounted the states are lost. It’s possible that on an iPad both might get rendered depending on the orientation of the device.

We can fix this by lifting the state higher and have both components share their state to ensure it doesn’t get lost. That’s not trivial right now but there are plans to update these components so I will try to address this issue once that work begins.

**Comment by axbom** [comment]
Wow that is super interesting. Thank you for responding so quickly and explaining the challenge in a way I can understand :) Good to have this back of mind when working on digital services.

**Comment by lukevella** [comment]
This should be fixed in #857
