### ISSUE TITLE
Existing votes not visible in mobile view

### ISSUE THREAD

**Issue by ionarn** [lukevella/rallly#485]
**Describe the bug**
When using mobile view of Rallly, already existing votes aren't visible.

**To Reproduce**
1. Open a poll with some votes on smartphone/mobile view (Example: https://rallly.co/p/MehgJcgQuHey)
2. switch to desktop view to see that this poll actually has votes

**Expected behavior**
Well, the votes should be visible in mobile view.

**Screenshots**
Mobile view:
![Mobile view](https://user-images.githubusercontent.com/37874454/217099176-884de412-a866-4d1a-aa70-2040cc5bed92.png)

Desktop view:
![Desktop view](https://user-images.githubusercontent.com/37874454/217099143-d72358ff-d7ba-42eb-844f-0550210a5341.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro, 64bit
 - Browser: Vivaldi
 - Version: 5.6.2867.62 (Stable channel) (64-bit)

**Smartphone (please complete the following information):**
 - Device: Redmi Note 9 Pro
 - OS: MIUI 13.0.2 (Android 12 SKQ1.211019.001)
 - Browser: Vivaldi
 - Version: 5.6.2868.36

**Additional Info**
I tried to fix this issue by deleting the cache of the browser on my mobile phone. That didn't fix anything.
I first encountered this issue today when checking how many votes there and noticed that the votes that yesterday still have been there, weren't there anymore. Or at least they seemed to have disappeared.
My guess is that this bug got introduced with the Rallly 2.0 update.

**Comment by lukevella** [comment]
Hi @ionarn, what's changed is that you no longer see existing votes while you are voting. This was done to avoid having nested clickable areas since previously there was a button you could click to show all the votes while you are voting. I agree that this is useful but it also caused some confusion as depending on where you are tapping you will get different behavior.

Before:

![CleanShot 2023-02-07 at 08 49 31](https://user-images.githubusercontent.com/676849/217196595-558a69a8-fd45-4abe-9db1-e1449d8049fb.gif)

In the new version, there is less info while you are voting but you can still see the results when you are not:

![CleanShot 2023-02-07 at 08 53 03](https://user-images.githubusercontent.com/676849/217197548-db73ea42-bcf6-4c16-9e5f-59d55bee2007.gif)

That said, I agree that showing some more information while voting is useful. As a start I'll include showing the score for each option.
