### ISSUE TITLE
Display version number somewhere on the app

### ISSUE THREAD

**Issue by lukevella** [lukevella/rallly#588]
Generally useful to be able to see what version is running.

## To do:
- [ ] Add a new environment `NEXT_PUBLIC_APP_VERSION`
- [ ] Update `apps/web/Dockerfile`  to pull the version from the root `package.json` and set this environment variable
- [ ] Show the value of this variable somewhere in the app

**Comment by arcticFox-git** [comment]
Hi Luke, I've been working through this today. I've got the version number to be below the logo in the footer in the form of v2.5.1 (so that it is language agnostic). Just working on pulling the version number from the `package.json` through the dockerfile as opposed to hardcoding `NEXT_PUBLIC_APP_VERSION` as an `.env` variable.

**Comment by lukevella** [comment]
@arcticFox-git excellent, thanks for picking this up 🙏
