### ISSUE TITLE
is this project dead?

### ISSUE THREAD

**Issue by sgohl** [lukevella/Rallly#91]
I could not manage to find an alternative, but Rallly seems to be dead for years now.
Not even the first `docker-compose up` step is working (not with node:10-alpine either)

Please archive the repository if it's meant to be dead and unmaintained.
In that case, some known alternatives?

Thanks!

**Comment by lukevella** [comment]
Hi @sgohl, the project isn't dead in the sense that I will try and keep it running for as long as I can but it I am not actively developing this version of Rallly mainly because I am working on a newer version which is a complete rewrite from the ground up. That said, development of the new version has been slow due to my personal circumstances but I'm hoping to be freed up to work on it full-time in the near future. I understand the situation is a bit frustrating and I apologize for that. If you have any advice on how this is best communicated, I am open to ideas.
