### ISSUE TITLE
Verification code always fails

### ISSUE THREAD

**Issue by ltguillaume** [lukevella/rallly#924]
**Describe the bug**
Just updated to **v3.2.0** and every verification code sent by mail fails.

**To Reproduce**
1. Fill in verification code received by mail
2. See: "Your verification code is incorrect or has expired"

**Expected behavior**
Just like the login URL, the verification code should work.

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: latest Chromium, latest Firefox

**Additional context**
Wondered about whether this had anything to do with timezone differences (Firefox + resist fingerprinting), but Chromium-based browser with the same timezone as the server also presents this issue.

**Comment by lukevella** [comment]
Can you confirm whether the base URL in your browser matches the base URL in the magic link?

**Comment by lukevella** [comment]
Yes I understood you. Thing is the verification code *does work* as well as can be seen on [app.rallly.co](https://app.rallly.co) which is the same version you are running. Usually what causes the behavior you are describing is trying to enter the verification code whilst accessing the app through a different URL from the one configured with `NEXT_PUBLIC_BASE_URL`. 

I'm not able to reproduce the behavior you are describing locally. There's also e2e tests in place to make sure this works. So it seems likely it's an issue with your configuration. Are you able to demonstrate the issue with a screen recording showing that the magic link URL and the page you're entering the verification code have the same base URL because it would be a waste of time to chase this otherwise.

**Comment by lukevella** [comment]
If you have a trailing `/` at the end of you `NEXT_PUBLIC_BASE_URL` you might want to remove that.

The only way I can reproduce the behavior you describe here and in #882 is by accessing the app with a different URL then what is configured in `NEXT_PUBLIC_BASE_URL`.

**Comment by lukevella** [comment]
> 1. Are you running via docker-compose as well?
Yes.
> 2. Maybe using nginx-proxy is contributing to this problem?
Most likely - if there is something wrong with your configuration.
> 3. Would there be any error logging if this occurs? I can check and post it here.
Check the network requests in your browser. I'd expect you to see a CORS error when submitting the verification code.
> It used to work fine in this configuration, though.
Under the hood, the authentication has been completely replaced from a bespoke implementation to next-auth. This is to allow us to support more auth methods down the line. Next-auth has some extra security features that prevent CORS attacks that weren't there before.

**Comment by lukevella** [comment]
Right, that makes sense. That's likely related to #849 then. i.e. the base url value for the link is being taken at build time rather than runtime. Explains why it works locally as well since I am running on localhost. I'll deploy a patch to fix this shortly.

**Comment by lukevella** [comment]
Can you let me know if `3.2.1` fixes this for you?
